# version: "3.9"
version: "3.7"

services:

  web:
    image: davidmcdonald93/docker-remote:robotreviewer
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
      - ./robotreviewer/config.json:/var/lib/deploy/config.json
    # configs:
    #   - source: rr-config
    #     target: /var/lib/deploy/config.json
    restart: unless-stopped
    command: web
    ports:
      - 5050:5000
    depends_on:
      - celery

  api:
    image: davidmcdonald93/docker-remote:robotreviewer
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
      - ./robotreviewer/config.json:/var/lib/deploy/config.json
    # configs:
    #   - source: rr-config
    #     target: /var/lib/deploy/config.json
    restart: unless-stopped
    command: api
    ports:
      - 5051:5001
    depends_on:
      - celery

  celery:
    image: davidmcdonald93/docker-remote:robotreviewer
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
      - ./robotreviewer/config.json:/var/lib/deploy/config.json
    # configs:
    #   - source: rr-config
    #     target: /var/lib/deploy/robotreviewer/config.json
    restart: unless-stopped
    command: celery
    depends_on:
      - rabbitmq
      - bert
      - grobid

  bert:
    image: davidmcdonald93/docker-remote:robotreviewer-bert
    # build: ./bert
    environment:
      - SCIBERT_PATH_MODEL=/var/lib/deploy/robotreviewer/data/scibert_scivocab_uncased
    volumes:
      - ./robotreviewer/data:/var/lib/deploy/robotreviewer/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672 
      - 15672:15672
    restart: unless-stopped
    volumes:
      - ./rabbitmq/:/etc/rabbitmq/

  grobid:
    image: grobid/grobid:0.6.2
    ports:
      - 8070:8070 # added to run outside docker service
    restart: unless-stopped

# configs:
#   rr-config:
#     file: ./robotreviewer/config.json
